# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'employeeEditWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets

from dbConnection import DBConnection


class Ui_EmployeeEditWindow(object):
    def setupUi(self, EmployeeEditWindow, SourceWindow, employee):
        EmployeeEditWindow.setObjectName("EmployeeEditWindow")
        EmployeeEditWindow.resize(402, 307)
        self.win2 = EmployeeEditWindow
        self.source = SourceWindow
        self.employee = employee
        self.dbConnection = DBConnection()
        self.centralwidget = QtWidgets.QWidget(EmployeeEditWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(-1, -1, 401, 211))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.label_6 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 5, 1, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 4, 1, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 3, 1, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 2, 1, 1, 1)
        self.textEdit_2 = QtWidgets.QTextEdit(self.gridLayoutWidget)
        self.textEdit_2.setObjectName("textEdit_2")
        self.textEdit_2.setText(employee.last)
        self.gridLayout.addWidget(self.textEdit_2, 1, 2, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 1, 1, 1)
        self.textEdit = QtWidgets.QTextEdit(self.gridLayoutWidget)
        self.textEdit.setObjectName("textEdit")
        self.textEdit.setText(employee.first)
        self.gridLayout.addWidget(self.textEdit, 0, 2, 1, 1)
        self.label = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 1, 1, 1)
        self.textEdit_3 = QtWidgets.QTextEdit(self.gridLayoutWidget)
        self.textEdit_3.setObjectName("textEdit_3")
        self.textEdit_3.setText(employee.email)
        self.gridLayout.addWidget(self.textEdit_3, 2, 2, 1, 1)
        self.textEdit_4 = QtWidgets.QTextEdit(self.gridLayoutWidget)
        self.textEdit_4.setObjectName("textEdit_4")
        self.textEdit_4.setText(employee.userName)
        self.gridLayout.addWidget(self.textEdit_4, 3, 2, 1, 1)
        self.textEdit_5 = QtWidgets.QTextEdit(self.gridLayoutWidget)
        self.textEdit_5.setObjectName("textEdit_5")
        self.textEdit_5.setText(employee.accountNumber)
        self.gridLayout.addWidget(self.textEdit_5, 4, 2, 1, 1)
        self.textEdit_6 = QtWidgets.QTextEdit(self.gridLayoutWidget)
        self.textEdit_6.setObjectName("textEdit_6")
        self.textEdit_6.setText(employee.routingNumber)
        self.gridLayout.addWidget(self.textEdit_6, 5, 2, 1, 1)
        self.pushButton = QtWidgets.QPushButton(self.centralwidget, clicked = lambda: self.save())
        self.pushButton.setGeometry(QtCore.QRect(10, 230, 121, 26))
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget, clicked = lambda: self.cancel())
        self.pushButton_2.setGeometry(QtCore.QRect(260, 230, 121, 26))
        self.pushButton_2.setObjectName("pushButton_2")
        EmployeeEditWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(EmployeeEditWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 402, 21))
        self.menubar.setObjectName("menubar")
        EmployeeEditWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(EmployeeEditWindow)
        self.statusbar.setObjectName("statusbar")
        EmployeeEditWindow.setStatusBar(self.statusbar)

        self.retranslateUi(EmployeeEditWindow)
        QtCore.QMetaObject.connectSlotsByName(EmployeeEditWindow)

    def retranslateUi(self, EmployeeEditWindow):
        _translate = QtCore.QCoreApplication.translate
        EmployeeEditWindow.setWindowTitle(_translate("EmployeeEditWindow", "Edit Employee"))
        self.label_6.setText(_translate("EmployeeEditWindow", "Routing Number"))
        self.label_5.setText(_translate("EmployeeEditWindow", "Account Number"))
        self.label_4.setText(_translate("EmployeeEditWindow", "User Name"))
        self.label_3.setText(_translate("EmployeeEditWindow", "Email"))
        self.label_2.setText(_translate("EmployeeEditWindow", "Last Name"))
        self.label.setText(_translate("EmployeeEditWindow", "First Name"))
        self.pushButton.setText(_translate("EmployeeEditWindow", "Save Changes"))
        self.pushButton_2.setText(_translate("EmployeeEditWindow", "Cancel Changes"))
    
    def save(self):
        newFirst = self.textEdit.toPlainText()
        newLast = self.textEdit_2.toPlainText()
        newEmail = self.textEdit_3.toPlainText()
        newUserName = self.textEdit_4.toPlainText()
        newAccoutNum = self.textEdit_5.toPlainText()
        newRoutingNum = self.textEdit_6.toPlainText()
        self.dbConnection.update_employee(self.employee.id, newFirst, newLast, newEmail, newUserName, newAccoutNum, newRoutingNum)
        from employerView import Ui_MainWindow
        self.win = QtWidgets.QMainWindow()
        self.ui = Ui_MainWindow()
        self.ui.setupUi(self.win, self.win2)
        
        self.source.close()
        self.win.show()
        
    def cancel(self):
        self.win2.close()


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    EmployeeEditWindow = QtWidgets.QMainWindow()
    ui = Ui_EmployeeEditWindow()
    ui.setupUi(EmployeeEditWindow)
    EmployeeEditWindow.show()
    sys.exit(app.exec_())
