# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'messages.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from dbConnection import DBConnection


class Ui_MessagesWindow(object):
    def setupUi(self, MessagesWindow, userid):
        MessagesWindow.setObjectName("MessagesWindow")
        MessagesWindow.resize(430, 475)
        self.dbConnection = DBConnection()
        self.userID = userid
        self.centralwidget = QtWidgets.QWidget(MessagesWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.listView = QtWidgets.QListView(self.centralwidget)
        self.listView.setGeometry(QtCore.QRect(0, 0, 431, 411))
        self.listView.setObjectName("listView")
        MessagesWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MessagesWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 430, 21))
        self.menubar.setObjectName("menubar")
        MessagesWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MessagesWindow)
        self.statusbar.setObjectName("statusbar")
        MessagesWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MessagesWindow)
        
        QtCore.QMetaObject.connectSlotsByName(MessagesWindow)

    def retranslateUi(self, MessagesWindow):
        _translate = QtCore.QCoreApplication.translate
        MessagesWindow.setWindowTitle(_translate("MessagesWindow", "MainWindow"))
        
    def populateList(self):
        cursor = self.dbConnection.get_messages(self.userID)
        for entitity in cursor:
            message = e

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MessagesWindow = QtWidgets.QMainWindow()
    ui = Ui_MessagesWindow()
    ui.setupUi(MessagesWindow)
    MessagesWindow.show()
    sys.exit(app.exec_())
