# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'punch.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from dbConnection import DBConnection

class Ui_PunchWindow(object):
    def setupUi(self, PunchWindow):
        self.dbConnection = DBConnection()
        PunchWindow.setObjectName("PunchWindow")
        PunchWindow.resize(281, 258)
        self.centralwidget = QtWidgets.QWidget(PunchWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget, clicked=lambda: self.getPunchType())
        self.pushButton.setGeometry(QtCore.QRect(90, 60, 81, 26))
        self.pushButton.setObjectName("pushButton")
        PunchWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(PunchWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 281, 21))
        self.menubar.setObjectName("menubar")
        PunchWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(PunchWindow)
        self.statusbar.setObjectName("statusbar")
        PunchWindow.setStatusBar(self.statusbar)

        self.retranslateUi(PunchWindow)
        QtCore.QMetaObject.connectSlotsByName(PunchWindow)

    def retranslateUi(self, PunchWindow):
        _translate = QtCore.QCoreApplication.translate
        PunchWindow.setWindowTitle(_translate("PunchWindow", "MainWindow"))
        self.pushButton.setText(_translate("PunchWindow", "Clock In"))
        
    def getPunchType(self):
        type = self.dbConnection.get_last_punch(6)
        print(type)
        if(type == 'out'):
            self.punchIn()
        else:
            self.punchOut()
            
    def punchIn(self):
        self.dbConnection.punch(6, 'in')
        
    def punchOut(self):
        self.dbConnection.punch(6, 'out')

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    PunchWindow = QtWidgets.QMainWindow()
    ui = Ui_PunchWindow()
    ui.setupUi(PunchWindow)
    PunchWindow.show()
    sys.exit(app.exec_())
